[WIP]インクリメンタルサーチの実装
nnn-dream-vegas/chat-space pull request #3
Opened 2019-03-16 17:28 UTC by nnn-dream-vegas

#WHAT
インクリメンタルサーチを実装

＃WHY
グループ作成時に検索が簡単になる為

2019-03-17 02:06 UTC, ghost requested changes
実際に動いてるところを見たいのでgifを貼ってください

2019-03-17 02:06 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +    format.json
インデント一個奥です

2019-03-17 02:06 UTC, hiroki5123 commented on app/assets/javascripts/group.js
> +       appendUserToSearch(user);
インデント一個奥です

2019-03-18 11:43 UTC, nnn-dream-vegas commented
https://gyazo.com/b73374df50e8b560c2730e0c7b1d0ce4

2019-03-18 11:50 UTC, ghost requested changes

2019-03-18 11:50 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +    format.json
こちらpushされていない、もしくは修正されていなさそうですが、いかがでしょうか？

2019-03-18 11:50 UTC, hiroki5123 commented on app/assets/javascripts/group.js
> +      appendUserToSearch(user);
eachの中はインデント一個奥にしましょう

2019-03-18 16:02 UTC, nnn-dream-vegas commented on app/controllers/users_controller.rb
> +    format.json
一番奥というのはdefを一番左端にするということでしょうか？

2019-03-19 11:15 UTC, merged